baseURL = "http://kuzimoto.com/"
languageCode = "en-us"
title = "kuzi's Weblog"
defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
MetaDataFormat = "toml"
enableGitInfo = true
theme = "kuzimoto"
