baseURL = "http://kuzimoto.com/"
languageCode = "en-us"
title = "kuzi's Blog"
defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
MetaDataFormat = "toml"
enableGitInfo = true
theme = "kuzimoto"
[params]
  author = "Kuzma Fesenko"
  description = "The personal blog of Kuzma Fesenko."
